# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808381192c12bce3c092e592cffb367b9a0449da62cdd471b30a9f7233033dce77380fcb5d773df0023e5d1d5495992b74668db4f275335ac2ac639f041daf72

test:
  secret_key_base: bbeffa07616cf18c5242e6c738ae0b89fc81b64dd1d183f4b0565b932b05b5fb5da0d652427b1bdf2a442c8d1ba9e0b37eacc343a1f03af6ad37808a571b6a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
